<?php
use common\models\Options;
use frontend\models\Article;
use frontend\models\FriendlyLink;
use frontend\models\ArticleContent;
use frontend\widgets\ArticleListView;
use frontend\widgets\ScrollPicView;
use common\widgets\JsBlock;
use frontend\assets\IndexAsset;
use yii\data\ArrayDataProvider;
use yii\data\Pagination;
use yii\widgets\LinkPager;
IndexAsset::register($this);
$this->title = ( !empty($category) ? $category . " - " : "" ) . Yii::$app->feehi->website_title;
?>
<!--中间内容一-->
<div class="list">
  <div class="width1178 clearfix">

<!-- 左边开始 -->
    <div class="sidebar_left">
        <div class="column bj_survey">合作院校</div>
        <ul class="menu">
        <li><a class="on" href="<?php echo Yii::$app->urlManager->createUrl(["article/hzyx"])?>">合作院校</a></li>
        </ul>
    </div>
<!-- 左边结束-->

    <!-- 右边开始 -->
    <div class="content_right">
          <h2>合作院校</h2>
         <div class="hzyx">
            <h3 class="up" id="two1" onmouseover="setContentTab('two',1,7)">东北地区</h3>
            <h3 id="two2" onmouseover="setContentTab('two',2,7)">华北地区</h3>
            <h3 id="two3" onmouseover="setContentTab('two',3,7)">华中地区</h3>
            <h3 id="two4" onmouseover="setContentTab('two',4,7)">华东地区</h3>
            <h3 id="two5" onmouseover="setContentTab('two',5,7)">华南地区</h3>
            <h3 id="two6" onmouseover="setContentTab('two',6,7)">西南地区</h3>
            <h3 id="two7" onmouseover="setContentTab('two',7,7)">西北地区</h3>
            <div class="clear"></div>
            <!--东北地区-->
            <div class="block" id="con_two_1">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" valign="middle"><strong>辽宁</strong></td>
    <td align="center" valign="middle"><strong>吉林</strong></td>
    <td align="center" valign="middle"><strong>黑龙江</strong></td>
  </tr>
  <tr>
    <td align="left" valign="middle">辽宁机电职业技术学院</td>
    <td align="left" valign="middle">长春市机械工业学校</td>
    <td align="left" valign="middle"><a href="/view/139.html" target="_blank">黑龙江职业学院</a></td>
  </tr>
  <tr>
    <td align="left" valign="middle"><a href="/view/133.html" target="_blank">辽宁石油化工大学职业技术学院</a></td>
    <td align="left" valign="middle">吉林电子信息职业技术学院</td>
    <td align="left" valign="middle">黑龙江农业工程职业学院</td>
  </tr>
  <tr>
    <td align="left" valign="middle">大连经济开发区职业中专</td>
    <td align="left" valign="middle">延边工业学校</td>
    <td align="left" valign="middle">哈尔滨工业大学实业技术培训中心</td>
  </tr>
  <tr>
    <td align="left" valign="middle">沈阳大学工商管理学院</td>
    <td align="left" valign="middle">吉林省城市建设学校</td>
    <td align="left" valign="middle">黑龙江煤炭职业技术学院</td>
  </tr>
  <tr>
    <td align="left" valign="middle">辽东学院</td>
    <td align="left" valign="middle">吉林省白城卓越电脑学校</td>
    <td align="left" valign="middle">佳木斯职业学院</td>
  </tr>
  <tr>
    <td align="left" valign="middle">沈阳工业大学辽阳校区</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">齐齐哈尔职业学院</td>
  </tr>
  <tr>
    <td align="left" valign="middle">沈阳工程学院培训中心</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">齐齐哈尔铁路工程学校</td>
  </tr>
  <tr>
    <td align="left" valign="middle">辽宁大学物理学院</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">齐齐哈尔职业技术教育中心学校</td>
  </tr>
  <tr>
    <td align="left" valign="middle">辽宁省交通高等专科学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">双鸭山市职业技术学校</td>
  </tr>
  <tr>
    <td align="left" valign="middle">大连现代技术中等职业学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">哈尔滨工业美术设计学校</td>
  </tr>
  <tr>
    <td align="left" valign="middle">辽宁科技大学高职学院</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">黑龙江省水利水电学校</td>
  </tr>
  <tr>
    <td align="left" valign="middle">沈阳建筑大学计算中心</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">黑龙江省哈尔滨现代职业技能培训学校</td>
  </tr>
  <tr>
    <td align="left" valign="middle">沈阳化工学院计算机学院</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">哈尔滨创意电脑职业技术培训学校</td>
  </tr>
  <tr>
    <td align="left" valign="middle">沈阳铁路机械学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">哈尔滨市南岗区能源微机外语学校</td>
  </tr>
  <tr>
    <td align="left" valign="middle">渤海船舶职业学院</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">齐齐哈尔蓝海培训中心</td>
  </tr>
  <tr>
    <td align="left" valign="middle">辽阳市辽化技工学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">黑龙江理工职业技能培训中心</td>
  </tr>
  <tr>
    <td align="left" valign="middle">沈阳市装备制造工程学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">黑龙江舜禹教育咨询有限公司</td>
  </tr>
  <tr>
    <td align="left" valign="middle">朝阳工程技术学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">黑龙江科技学院</td>
  </tr>
  <tr>
    <td align="left" valign="middle">本溪机电工程学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">黑龙江工商职业技术学院</td>
  </tr>
  <tr>
    <td align="left" valign="middle">辽宁省机电工程学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="middle">营口农业工程学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="middle">大连市轻工业学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="middle">大连市旅顺口区职业教育中心</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="middle">大连市交通口岸职业技术学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="middle">大连电子学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="middle">庄河市职教中心</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="middle">本溪市东方计算机信息技术学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="middle">辽宁省阜新市联宇电脑培训学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td align="left" valign="middle">创想计算机培训学校</td>
    <td align="left" valign="middle">&nbsp;</td>
    <td align="left" valign="middle">&nbsp;</td>
  </tr>
           </table>
           </div>
           <!--华北地区-->
           <div id="con_two_2">
             <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><strong>北京</strong></td>
    <td align="center"><strong>天津</strong></td>
    <td align="center"><strong>河北</strong></td>
    <td align="center"><strong>内蒙</strong></td>
    <td align="center"><strong>山西</strong></td>
  </tr>
  <tr>
    <td>北京汽车工业学校</td>
    <td>天津城市建设学院高职学院</td>
    <td><a href="/view/140.html" target="_blank">河北机电职业技术学院</a></td>
    <td>包头职业技术学院</td>
    <td>太原理工大学教育技术中心</td>
  </tr>
  <tr>
    <td>北京城建学校</td>
    <td>天津市津苏进修学院</td>
    <td>河北省机电职业技术学院</td>
    <td>内蒙古工业大学电力学院</td>
    <td>山西长治职业技术学院</td>
  </tr>
  <tr>
    <td>北京市电子工业学校</td>
    <td>天津劳动保护学校</td>
    <td>石家庄市职业技术教育中心</td>
    <td>河套大学土木工程学院</td>
    <td>山西建筑职业技术学院</td>
  </tr>
  <tr>
    <td>北京市机械工业学校</td>
    <td>天津市第一轻工业学校</td>
    <td>秦皇岛职业技术学院</td>
    <td>内蒙古科技大学</td>
    <td>山西工程职业技术学院</td>
  </tr>
  <tr>
    <td>北京市化工学校</td>
    <td>天津机电工业学校</td>
    <td>河北理工大学交通与测绘学院</td>
    <td>内蒙古机电职业技术学院</td>
    <td>吕梁高等专科学校</td>
  </tr>
  <tr>
    <td>北京水利水电学校</td>
    <td>天津市东丽职业教育中心学校</td>
    <td>河北师范大学</td>
    <td>内蒙古建筑职业技术学院</td>
    <td>山西综合职业技术学院</td>
  </tr>
  <tr>
    <td><a href="/view/134.html" target="_blank">北京工业职业技术学院</a></td>
    <td>天津亿创宏达科技有限公司</td>
    <td>河北科技大学经济管理学院</td>
    <td>内蒙古民族大学</td>
    <td>太原理工大学长治学院</td>
  </tr>
  <tr>
    <td><a href="/view/136.html" target="_blank">北京工贸技师学院</a></td>
    <td>天津市泛德信息技术职业培训学校</td>
    <td>中国地质大学长城学院</td>
    <td>内蒙古电子信息职业技术学院</td>
    <td>太原电力高等专科学校</td>
  </tr>
  <tr>
    <td>北京京北职业技术学院</td>
    <td>&nbsp;</td>
    <td>石家庄外经贸职业学院</td>
    <td>乌海职业技术学院</td>
    <td>山西农业大学工程技术学院</td>
  </tr>
  <tr>
    <td>华北科技学院</td>
    <td>&nbsp;</td>
    <td>渤海石油职业学院</td>
    <td>内蒙古工业大学</td>
    <td>山西综合职业技术学院数控分院</td>
  </tr>
  <tr>
    <td>北京邮电大学世纪学院</td>
    <td>&nbsp;</td>
    <td>河北建筑工程学院</td>
    <td>河套大学国际学院</td>
    <td>中北大学</td>
  </tr>
  <tr>
    <td>房山区职业学校</td>
    <td>&nbsp;</td>
    <td>中国环境管理干部学院</td>
    <td>内蒙古西北电力学校</td>
    <td>山西省晋城市高级技工学校</td>
  </tr>
  <tr>
    <td>北京工商管理专修学院</td>
    <td>&nbsp;</td>
    <td>衡水职教中心</td>
    <td>内蒙古八维职业技能培训学校</td>
    <td>太原理工大学计算机与软件学院</td>
  </tr>
  <tr>
    <td>中国管理软件学院</td>
    <td>&nbsp;</td>
    <td>北方机电工业学校</td>
    <td>内蒙古根河市盛世电脑学校</td>
    <td>太原市万柏林区电子技术学校</td>
  </tr>
  <tr>
    <td>北京铁路电气化学校</td>
    <td>&nbsp;</td>
    <td>承德工业学校</td>
    <td>远方名博外语信息学校</td>
    <td>太原理工大学机械工程学院</td>
  </tr>
  <tr>
    <td>北京市自动化工程学校</td>
    <td>&nbsp;</td>
    <td>唐山市丰南区职业技术教育中心</td>
    <td>呼和浩特市宇杰职业培训学校</td>
    <td>太原科技大学</td>
  </tr>
  <tr>
    <td>北京市昌平职业学校</td>
    <td>&nbsp;</td>
    <td>阜平县职业技术教育中心</td>
    <td>呼市创新技术公司</td>
    <td>太原理工大学材料学院</td>
  </tr>
  <tr>
    <td>北京金色阳光计算机技术培训中心</td>
    <td>&nbsp;</td>
    <td>河北省科技工程学校</td>
    <td>内蒙古赤峰新起点职业技术培训学校</td>
    <td>山西省贸易学校</td>
  </tr>
  <tr>
    <td>千禧艺海数码科技有限公司</td>
    <td>&nbsp;</td>
    <td>邯郸市职业教育中心</td>
    <td>天正昕电脑培训中心</td>
    <td>华北机电学校</td>
  </tr>
  <tr>
    <td>北京市华嘉教育发展有限公司</td>
    <td>&nbsp;</td>
    <td>河北省邢台市工业学校</td>
    <td>内蒙古曙光科技人才中心</td>
    <td>高平市职业中学</td>
  </tr>
  <tr>
    <td>北京市京博文电脑培训学校</td>
    <td>&nbsp;</td>
    <td>张家口机械工业学校</td>
    <td>内蒙古呼和浩特市翼翔教育科技有限公司</td>
    <td>平遥县职业学校</td>
  </tr>
  <tr>
    <td>北京新世纪电脑培训学校</td>
    <td>&nbsp;</td>
    <td>冀州市创意电脑学校</td>
    <td>包头华大电脑学校</td>
    <td>太原铁路机械学校</td>
  </tr>
  <tr>
    <td>北京物贸职工学院</td>
    <td>&nbsp;</td>
    <td>邯郸市信华电脑学校</td>
    <td>锡林浩特市九维计算机培训中心</td>
    <td>金诺计算机学校</td>
  </tr>
  <tr>
    <td>北京建工培训中心</td>
    <td>&nbsp;</td>
    <td>秦皇岛市天恒计算机技能培训学校</td>
    <td>内蒙古呼和浩特市超艺电脑培训学校</td>
    <td>榆次华箐计算机培训中心</td>
  </tr>
  <tr>
    <td>北京联合大学</td>
    <td>&nbsp;</td>
    <td>河北廊坊艺帆电脑培训学校</td>
    <td>赤峰博思电脑职业技能培训学校</td>
    <td>太原百大职业培训中心</td>
  </tr>
  <tr>
    <td>北京懿盛宏扬教育科技有限公司</td>
    <td>&nbsp;</td>
    <td>秦皇岛市创达职业培训学校</td>
    <td>呼市闻众传媒有限责任公司</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>北京恒润智典教育科技有限公司</td>
    <td>&nbsp;</td>
    <td>壹丁教育资讯</td>
    <td>海拉尔阳光电脑学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>北京市王码电脑培训中心</td>
    <td>&nbsp;</td>
    <td>唐山新博电脑职业技能培训学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>邯郸市科达电脑学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>燕山大学建工学院</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>廊坊市金东方职业培训学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>唐山市方圆计算机职业技能培训学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>石家庄工程技术学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
             </table>
           </div>
           <!--华中地区-->
           <div id="con_two_3">
             <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><strong>河南</strong></td>
    <td align="center"><strong><strong>湖南</strong></strong></td>
    <td align="center"><strong>湖北</strong></td>
  </tr>
  <tr>
    <td>河南平顶山工业职业技术学院</td>
    <td>湖南邵阳学院机械工程学院</td>
    <td>湖北恩施职业技术学院</td>
  </tr>
  <tr>
    <td>河南工业职业技术学院</td>
    <td>湖南人文科技学院</td>
    <td>武汉仪表电子学校</td>
  </tr>
  <tr>
    <td>平顶山工学院</td>
    <td>湖南永州育才科技专校</td>
    <td>湖北城市建设职业技术学院</td>
  </tr>
  <tr>
    <td>河南农业大学机电工程学院</td>
    <td>邵阳市计算机学校</td>
    <td>湖北省襄樊市工业学校</td>
  </tr>
  <tr>
    <td>河南机电学校</td>
    <td>长沙理工大学</td>
    <td>黄冈职业技术学院</td>
  </tr>
  <tr>
    <td>郑州电力高等专科学校</td>
    <td>衡阳市工业职业学校</td>
    <td>黄石机电职业技术学院</td>
  </tr>
  <tr>
    <td>郑州工业贸易学校</td>
    <td>湖南省冷水江工业中等专业学校</td>
    <td>华中科技大学孝感科技分院</td>
  </tr>
  <tr>
    <td>河南省建筑工程学院</td>
    <td>望城县职业中专学校</td>
    <td>湖北国土资源职业学院</td>
  </tr>
  <tr>
    <td>郑州航空工业管理学院</td>
    <td>株洲市中等职业学校</td>
    <td>武钢中等职业技术学校</td>
  </tr>
  <tr>
    <td>长城铝业公司职工学院</td>
    <td>永州工商职业中专学校</td>
    <td>武汉机电工程学校</td>
  </tr>
  <tr>
    <td>河南工业大学化学工业职业学院</td>
    <td>岳阳县职业中专学校</td>
    <td>十堰市高级技工学校</td>
  </tr>
  <tr>
    <td>郑州铁路职业技术学院</td>
    <td>潭县第二职业中专</td>
    <td>仙桃市创源计算机科技中等职业学校</td>
  </tr>
  <tr>
    <td>黄河科技学院</td>
    <td>慈利县职业中专学校</td>
    <td>郧阳科技学校</td>
  </tr>
  <tr>
    <td>河南经贸职业学院</td>
    <td>湖南省怀化工业中等专业学校</td>
    <td>湖北省黄冈劳动中专</td>
  </tr>
  <tr>
    <td>郑州科技职业学院</td>
    <td>长沙民政职业技术学院</td>
    <td>武穴理工中等专业学校</td>
  </tr>
  <tr>
    <td>郑州经济管理干部学院</td>
    <td>湖南省常宁市职业中等专业学校</td>
    <td>湖北省机械工业学校</td>
  </tr>
  <tr>
    <td>河南机电高等专科学校</td>
    <td>益阳晓宇电脑学校</td>
    <td>湖北省襄樊市机电工程学校</td>
  </tr>
  <tr>
    <td>平原大学</td>
    <td>沅陵县三维电脑职业技术学校</td>
    <td>江汉石油高级技校</td>
  </tr>
  <tr>
    <td>河南科技学院</td>
    <td>&nbsp;</td>
    <td>恩施州交通技工学校</td>
  </tr>
  <tr>
    <td>河南工程技术学校</td>
    <td>&nbsp;</td>
    <td>黄冈职业技术学院中专部</td>
  </tr>
  <tr>
    <td>河南理工大学</td>
    <td>&nbsp;</td>
    <td>鄂州职业大学</td>
  </tr>
  <tr>
    <td>河南省焦作师范高等专科学院</td>
    <td>&nbsp;</td>
    <td>武汉市第一职业教育中心</td>
  </tr>
  <tr>
    <td>黄淮学院</td>
    <td>&nbsp;</td>
    <td>荆州市工业学校</td>
  </tr>
  <tr>
    <td>河南省驻马店财经学校</td>
    <td>&nbsp;</td>
    <td>阳新县职业教育中心</td>
  </tr>
  <tr>
    <td>河南科技大学机电学院</td>
    <td>&nbsp;</td>
    <td>秭归县职业教育中心 </td>
  </tr>
  <tr>
    <td>洛阳师范学院</td>
    <td>&nbsp;</td>
    <td>东风高级技工学校</td>
  </tr>
  <tr>
    <td>河南省三门峡中等专业学校</td>
    <td>&nbsp;</td>
    <td>崇阳县职业教育中心</td>
  </tr>
  <tr>
    <td>河南省南阳工业学校</td>
    <td>&nbsp;</td>
    <td>湖北城市职业学校</td>
  </tr>
  <tr>
    <td>黄河水利职业技术学院</td>
    <td>&nbsp;</td>
    <td>武汉市第二轻工业学校</td>
  </tr>
  <tr>
    <td>商丘科技职业学院</td>
    <td>&nbsp;</td>
    <td>十堰市计算机技术学校</td>
  </tr>
  <tr>
    <td>鹤壁职业技术学院</td>
    <td>&nbsp;</td>
    <td>建始县三人行电脑学校</td>
  </tr>
  <tr>
    <td>郑州交通职业学院</td>
    <td>&nbsp;</td>
    <td>武汉今天职业培训学校</td>
  </tr>
  <tr>
    <td>焦作建筑经济学校</td>
    <td>&nbsp;</td>
    <td>武汉旭阳电脑培训有限公司</td>
  </tr>
  <tr>
    <td>开封大学</td>
    <td>&nbsp;</td>
    <td>武汉飞达电脑技术培训学校</td>
  </tr>
  <tr>
    <td>三门峡职业技术学院</td>
    <td>&nbsp;</td>
    <td>武汉思创信息服务部</td>
  </tr>
  <tr>
    <td> 郑州华信职业技术学院</td>
    <td>&nbsp;</td>
    <td>佳枫职业教育培训学校 </td>
  </tr>
  <tr>
    <td>中州大学</td>
    <td>&nbsp;</td>
    <td>湖北华庭科技计算机有限公司</td>
  </tr>
  <tr>
    <td>河南轻工业学院</td>
    <td>&nbsp;</td>
    <td>湖北省十堰金东方计算机培训学校</td>
  </tr>
  <tr>
    <td>华北水利水电学院</td>
    <td>&nbsp;</td>
    <td>湖北省创想计算机教育中心</td>
  </tr>
  <tr>
    <td>安阳工学院继续教育学院</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>郑州轻工业学院继续教育学院</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>永城职业学院</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南新野航运职业技术学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南省新乡工业贸易学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南省安阳市亚太职业培训学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南信息工程学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南省郑州水利学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南省化学工业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南辅读中等职业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南省财经学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南省工业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>洛阳经济学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>洛阳铁路信息工程学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南省经济管理学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南省理工学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南省轻工业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>郑州市财税学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>郑州市电子信息工程学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>郑州市国防科技学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>郑州市信息技术学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>驻马店机械电子工程学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>濮阳市职业中等专业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>新乡市第一职业中专</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>孟州市职业中等专业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>新郑市中等专业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>郑州机电工程学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>登封市中等专业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>罗山县中等职业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>濮阳县职业技术学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>灵宝市职业中等专业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>新密市职教中心</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>中牟县职业中等专业学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>邓州市职业教育中心</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>固始县职业教育中心</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>固始县职业中专</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>开封市技师学院校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>开封大学计算机教学部</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>洛阳同德电脑培训学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南南洋教育科技有限公司</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>河南省开封市长城同方计算机职业培训学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>郑州信息科技职业学院</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
             </table>
           </div>
           <!--华东地区-->
           <div id="con_two_4">
             <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><strong>江苏</strong></td>
    <td align="center"><strong>浙江</strong></td>
    <td align="center"><strong>安徽</strong></td>
    <td align="center"><strong>山东</strong></td>
    <td align="center"><strong>上海</strong></td>
  </tr>
  <tr>
    <td>徐州市机电工程高等职业学校</td>
    <td>宁海县高级职业技术中心学校</td>
    <td>安徽国防科技职业学院</td>
    <td>山东理工大学</td>
    <td>上海医疗器械高等专科学校</td>
  </tr>
  <tr>
    <td>常州铁道高等职业技术学校</td>
    <td>缙云县职业中专</td>
    <td>安徽工业经济职业技术学院</td>
    <td>淄博职业学院</td>
    <td>上海电机技术高等专科学校</td>
  </tr>
  <tr>
    <td>建东职业技术学院</td>
    <td>余姚市职业技术学校</td>
    <td>安徽交通职业技术学院</td>
    <td>高青县职业教育中心</td>
    <td><a href="/view/137.html" target="_blank">上海市工业技术学校</a></td>
  </tr>
  <tr>
    <td>徐州建筑职业技术学院</td>
    <td>余姚市职成教中心学校</td>
    <td>芜湖职业技术学院</td>
    <td>济南电子机械工程学校</td>
    <td align="center"><strong>江西</strong></td>
  </tr>
  <tr>
    <td>江苏盐城第一职业高级中学</td>
    <td>乐清市虹桥职业学校</td>
    <td>蚌埠机械学校</td>
    <td>山东省胶南市高级职业技术学校</td>
    <td>江西省计算机培训学院</td>
  </tr>
  <tr>
    <td>海安双楼职业高级中学</td>
    <td>宁波职教中心</td>
    <td>安徽商贸职业技术学院</td>
    <td>山东商业职业技术学院</td>
    <td>鹰潭广播电视大学现代教育网络信息中心</td>
  </tr>
  <tr>
    <td>徐州工程学院</td>
    <td>余杭临平职高</td>
    <td>安徽省池州师范专科学校</td>
    <td>山东淄博工业学校</td>
    <td>江西井冈山学院工学院</td>
  </tr>
  <tr>
    <td><a href="/view/138.html" target="_blank">南京交通职业技术学院</a></td>
    <td> 德清职业中专</td>
    <td>安徽马鞍山职业教育中心</td>
    <td>山东纺织职业学院继续教育学院</td>
    <td>鹰潭职业技术学院</td>
  </tr>
  <tr>
    <td>江苏省昆山登云科技职业学院</td>
    <td>椒江职业中专</td>
    <td>六安振华计算机中专学校</td>
    <td>威海职业学院</td>
    <td>江西省江西冶金技师学院</td>
  </tr>
  <tr>
    <td>淮阴工学院</td>
    <td>新昌职业技术学校</td>
    <td>安徽省泗县五中</td>
    <td>临沂师范学院</td>
    <td>江西经济管理干部学院</td>
  </tr>
  <tr>
    <td>宿迁职业技术学院</td>
    <td>奉化职业教育中心学校</td>
    <td>安徽省马鞍山工业学校</td>
    <td>烟台职业学院</td>
    <td>江西大宇职业技术学院</td>
  </tr>
  <tr>
    <td>炎黄职业技术学院</td>
    <td>东阳市技术学校</td>
    <td>安徽宿州市第一职业高中</td>
    <td>中澳合作山东艺术设计学院</td>
    <td>江西赣江职业技术学院</td>
  </tr>
  <tr>
    <td>盐城工学院</td>
    <td>临海中等职业技术学校</td>
    <td>铜陵职业技术学院</td>
    <td>烟台大学数学与信息科学学院</td>
    <td><a href="/view/141.html" target="_blank">江西应用技术职业学院</a></td>
  </tr>
  <tr>
    <td>盐城纺织职业技术学院</td>
    <td>浙江上虞市职业中专</td>
    <td>安徽财贸职业学院</td>
    <td>烟台工程职业技术学院</td>
    <td>江西省电子信息工程学校</td>
  </tr>
  <tr>
    <td>无锡科技职业学院</td>
    <td>浙江省商业职业技术学院</td>
    <td>安徽工业职业技术学院</td>
    <td>德州职业技术学院</td>
    <td>南昌市第一中等专业学校</td>
  </tr>
  <tr>
    <td>江苏省泰兴职业教育中心校</td>
    <td>浙江省温岭市社区学院</td>
    <td>安徽职业技术学院</td>
    <td>山东省临沂第一职业中等专业学校</td>
    <td>江西机电学校</td>
  </tr>
  <tr>
    <td>江苏省涟水职业高级中学</td>
    <td>长兴县职业教育中心学校</td>
    <td>皖西学院</td>
    <td>山东华宇学院</td>
    <td>萍乡市工业中等专业学校</td>
  </tr>
  <tr>
    <td>江苏省徐州市经济开发区工业学校</td>
    <td>温岭市职业技术学校</td>
    <td>宿州职业技术学院</td>
    <td>山东工商学院</td>
    <td>江西中山电子计算机中等专业学校</td>
  </tr>
  <tr>
    <td>江苏工贸高级技工学校</td>
    <td>衢州中等专业学校</td>
    <td>安徽建筑工业学院</td>
    <td>菏泽技术学院</td>
    <td>上饶市中等专业学校</td>
  </tr>
  <tr>
    <td>江苏新沂职教中心</td>
    <td>温州市职业中等专业学校</td>
    <td>滁州职业技术学院</td>
    <td>潍坊科技学院</td>
    <td>赣州市第一职业技术学校</td>
  </tr>
  <tr>
    <td>镇江高等职业技术学校</td>
    <td>永康市职业技术学校</td>
    <td>安徽经济管理学院</td>
    <td>平度职教中心</td>
    <td>南昌工业学校</td>
  </tr>
  <tr>
    <td>南京江宁中等专业学校</td>
    <td>浙江科技工程学校</td>
    <td>安徽省巢湖职业技术学院</td>
    <td>青岛交通职业学校</td>
    <td>江西省临川现代教育学校</td>
  </tr>
  <tr>
    <td>徐州市职业教育中心</td>
    <td>金华市第一中等职业学校</td>
    <td>铜陵智通职业技术学校</td>
    <td>即墨市第一职业中等专业学校</td>
    <td>江西省黎川县职业中专</td>
  </tr>
  <tr>
    <td>常州市刘国钧职业教育中心</td>
    <td>浙江信息工程学校</td>
    <td>万博科技职业学院</td>
    <td>青岛商务学校</td>
    <td>九江科技中专</td>
  </tr>
  <tr>
    <td>苏州高等职业技术学校</td>
    <td>丽水市职业高级中学</td>
    <td>宁国市精英电脑职业学校</td>
    <td>沂水县职教中心</td>
    <td>江西育通教育发展有限公司</td>
  </tr>
  <tr>
    <td>南通市中等专业学校</td>
    <td>绍兴县职教中心</td>
    <td>安徽兴鹏科技学校</td>
    <td>滨州市滨城区职教中心</td>
    <td>斯达模具设计培训</td>
  </tr>
  <tr>
    <td>连云港市职业技术教育中心</td>
    <td>义乌市城镇职业技术学校</td>
    <td>芜湖工业学校</td>
    <td>嘉祥职业中专</td>
    <td>吉安市蓝天职业培训中心</td>
  </tr>
  <tr>
    <td>盐城市盐南中等专业学校</td>
    <td>舟山职业技术学校</td>
    <td>六安市同创职业学校</td>
    <td>聊城工业学校</td>
    <td align="center"><strong>福建</strong></td>
  </tr>
  <tr>
    <td>扬州高等职业技术学校</td>
    <td>绍兴市职教中心</td>
    <td>安徽广播影视职业技术学院</td>
    <td>烟台经济技术开发区高级职业技术学校</td>
    <td>福建工业学校</td>
  </tr>
  <tr>
    <td>泰州机电高等职业技术学校</td>
    <td>海盐县职成教中心</td>
    <td>安徽理工大学</td>
    <td>山东省济阳县职业中等专业学校</td>
    <td>福建理工学校</td>
  </tr>
  <tr>
    <td>宿迁市职教中心</td>
    <td>衢江区职业中专</td>
    <td>安徽三联学院</td>
    <td>烟台城乡建设学校</td>
    <td>福州旅游职业中专学校</td>
  </tr>
  <tr>
    <td>江苏省无锡立信职教中心校</td>
    <td>宁波鄞州区职业教育中心学校</td>
    <td>安徽水利水电职业技术学院</td>
    <td>济南第二职业中专</td>
    <td>南安职业中专学校</td>
  </tr>
  <tr>
    <td>苏州工业用园区工业技术学校</td>
    <td>浙江省龙游欣浪电脑学校</td>
    <td>中国科学院合肥科学技术学校</td>
    <td>定陶县职业教育中心</td>
    <td>晋江华侨职业中专学校</td>
  </tr>
  <tr>
    <td>淮安市高级职业技术学校</td>
    <td>浙江省玉环县世纪青年电脑培训学校</td>
    <td>安徽省肥东县职业教育中心</td>
    <td>滨州中等职业学校</td>
    <td>莆田华侨职业中专学校</td>
  </tr>
  <tr>
    <td>江苏省吴江中等专业学校</td>
    <td>杭州市团校</td>
    <td>濉溪中等中专学校（濉溪职教中心）</td>
    <td>日照市工业学校</td>
    <td>龙岩华侨职业中专学校</td>
  </tr>
  <tr>
    <td>江苏省常熟职业教育中心校</td>
    <td>金华阳光电脑培训中心</td>
    <td>蒙城职业高级中学</td>
    <td>济南市九职专</td>
    <td>漳州第二职业中专学校</td>
  </tr>
  <tr>
    <td>江苏省溧阳中等专业学校</td>
    <td>杭州思递波信息技术咨询有限公司</td>
    <td>亳州工业学校</td>
    <td>济宁市生物化工学校</td>
    <td>南平市农业学校</td>
  </tr>
  <tr>
    <td>无锡旅游商贸高等职业技术学校</td>
    <td>浙江省电子产品维修管理中心国家职业技能鉴定所</td>
    <td>安徽电子工程学校</td>
    <td>寿光市第一职业中专</td>
    <td>三明市农业学校</td>
  </tr>
  <tr>
    <td>江苏省昆山第二中等专业学校</td>
    <td>舟山普陀四通电脑培训中心</td>
    <td>六安市皖信职业学校</td>
    <td>山东纺织工业学校</td>
    <td>霞浦职业中专学校</td>
  </tr>
  <tr>
    <td>徐州生物工程职业技术学院</td>
    <td>浙江三联专修学院继续教育学院院</td>
    <td>蚌埠市新安职业学校</td>
    <td>济宁农业学校</td>
    <td>福建省邮电学校</td>
  </tr>
  <tr>
    <td>南京下关中等专业学校</td>
    <td>&nbsp;</td>
    <td>阜阳职业技术学院</td>
    <td>邹城高级职业技术学校</td>
    <td>福建省侨兴轻工学校</td>
  </tr>
  <tr>
    <td>南京博睿旭华科技有限公司</td>
    <td>&nbsp;</td>
    <td>宿州市中兴学校</td>
    <td>淄博公用事业技校</td>
    <td>福建省柘荣职业技术学校</td>
  </tr>
  <tr>
    <td>南京业林软件科技有限公司</td>
    <td>&nbsp;</td>
    <td>宁国市安南职业学校</td>
    <td>青岛工贸职业学校</td>
    <td>集美轻工业学校</td>
  </tr>
  <tr>
    <td>复纬科技苏州培训中心</td>
    <td>&nbsp;</td>
    <td>安徽电子信息职业技术学院</td>
    <td>山东省轻工工程学校</td>
    <td>福建省厦门电子职业中专学校</td>
  </tr>
  <tr>
    <td>南通升星职业技能培训中心</td>
    <td>&nbsp;</td>
    <td>安徽冶金科技职业学院</td>
    <td>菏泽市职业技术中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>启东市红旗电脑培训中心</td>
    <td>&nbsp;</td>
    <td>安徽亳州市智达职业技术学校</td>
    <td>潍坊交通技工学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>无锡市私立蓝天培训中心</td>
    <td>&nbsp;</td>
    <td>安徽城市建设学院</td>
    <td>郓城县职教中心</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>江苏徐州市英才教育培训中心</td>
    <td>&nbsp;</td>
    <td>亳州职业技术学院</td>
    <td>鄄城县职业技术教育中心</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>东台市计委计算机培训中心</td>
    <td>&nbsp;</td>
    <td>安徽铜陵新创职业学校</td>
    <td>山东省昌乐县职业中专</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>江苏省泰州市博日电脑技术学校</td>
    <td>&nbsp;</td>
    <td>合肥市求实职业学校</td>
    <td>山东省交通运输学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>江苏省东海县银河电脑学校</td>
    <td>&nbsp;</td>
    <td>涡阳县农机化技术学校</td>
    <td>商河县职业中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>徐州领航舰培训中心</td>
    <td>&nbsp;</td>
    <td>合肥英诺职业学校</td>
    <td>山东省兖州市技工学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>江苏省东台市小鸽子外语计算机培训中心</td>
    <td>&nbsp;</td>
    <td>安庆市第一职业与教育中心</td>
    <td>胶州市职业中专</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>南通市科技局生产力促进中心</td>
    <td>&nbsp;</td>
    <td>合肥建设学校</td>
    <td>蓬莱高职</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>江苏省泰兴通润信息技术培训中心</td>
    <td>&nbsp;</td>
    <td>安徽省汽车工业学校</td>
    <td>胶南市职业中专</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>江苏大丰市劳动就业培训中心</td>
    <td>&nbsp;</td>
    <td>安徽合肥电子学校</td>
    <td>济南市历城职业中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>连云港市新华职业技术学校</td>
    <td>&nbsp;</td>
    <td>合肥市职业教育中心</td>
    <td>山东省汶上县职业教育中心</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>南京奥博职业培训学校</td>
    <td>&nbsp;</td>
    <td>安徽电气工程学校</td>
    <td>长清职业中专</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>苏州振邦人才培训中心</td>
    <td>&nbsp;</td>
    <td>安徽经济技术学校</td>
    <td>济宁广播电视大学电视中专学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>江苏常州武进宏德教育培训中心</td>
    <td>&nbsp;</td>
    <td>安徽省宁国市职业高级中学</td>
    <td>济南铁路机械学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>烟台市机电技工学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>烟台市福山职业高级中学</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>济南第二职业中专</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>日照市工业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>山东济宁市生物化工学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>山东寿光市第一职业中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>山东纺织工业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>邹城高级职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>淄博公用事业技工学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>青岛工贸职业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>山东省轻工工程学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>山东省菏泽市职业技术中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>山东省潍坊交通技工学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>胶州市职业中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>蓬莱市高级职业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>山东省胶南市职业中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>济宁广播电视大学电视中专学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>济南铁路机械学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>烟台机电工程技工学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>威海工业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>潍坊第一职业中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>潍坊商业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>五莲职教中心</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>枣庄经济学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>枣庄市薛城区职业中专</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>德州信息工程中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>宁津县职业中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>山东省交通运输学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>济南市历城第二职业中专</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>淄川区职教中心</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>广饶县中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>烟台第一职业中专</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>山东电子商务教育</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>山东省企业培训考试中心职业教育发展部</td>
    <td>&nbsp;</td>
  </tr>
             </table>

           </div>
           <!--华南地区-->
           <div id="con_two_5">
             <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><strong>广东</strong></td>
    <td align="center"><strong>海南</strong></td>
  </tr>
  <tr>
    <td>广州市机电中等专业学校</td>
    <td>海口经济职业技术学院</td>
  </tr>
  <tr>
    <td>河源市职业技术学校</td>
    <td>海南省机电工程学校</td>
  </tr>
  <tr>
    <td>广州市航天科技技工学校</td>
    <td>海南省工业学校</td>
  </tr>
  <tr>
    <td>五邑大学</td>
    <td>海南万纵网络科技有限公司</td>
  </tr>
  <tr>
    <td>广东省南方高级技工学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>佛山市南海区信息技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东省工业贸易职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>佛山市顺德区梁銶琚职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东省理工职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东省轻工职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东省经济贸易职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东省海洋工程职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东省民政职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>肇庆市工业贸易学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>东莞理工学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>江门市新会区机电职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>惠州市工业科技学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东省财经职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东中山市中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广州市轻工职业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>清远市职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>韶关市中等职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>阳江市第一职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广州市交通运输职业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>惠州市博罗中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广州市黄埔职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东省农工商职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>珠海市理工职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>江门市第一职业高级中学</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>中山市沙溪理工学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东省石油化工职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>肇庆市科技中等职业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>顺德区中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>开平市机电中等职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>佛山市华材职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广东省高州市润通电脑培训学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>兴华职业培训学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>国家信息化计算机教育认证（肇庆）中心</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>台山市新天地职业培训学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广州市番禺区新希望电脑培训中心</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>深圳爱华人才培训中心</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>慧星职业技能培训中心</td>
    <td>&nbsp;</td>
  </tr>
</table>

           </div>
           <!--西南地区-->
           <div id="con_two_6">
             <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2" align="center"><strong>广西</strong></td>
    <td align="center"><strong>四川</strong></td>
  </tr>
  <tr>
    <td>广西机电职业技术学院</td>
    <td>广西航运学校</td>
    <td>四川建筑职业技术学院</td>
  </tr>
  <tr>
    <td>广西第一工业学校</td>
    <td>广西二轻工业管理学校</td>
    <td>四川水利职业技术学院</td>
  </tr>
  <tr>
    <td>广西机电工程学校</td>
    <td>广西柳州市交通学校</td>
    <td>四川工程职业技术学院</td>
  </tr>
  <tr>
    <td>广西水利电力职业技术学院</td>
    <td>玉林市模具制造技术学校</td>
    <td>绵阳职业技术学院</td>
  </tr>
  <tr>
    <td>广西机电工业学校</td>
    <td>来宾市职业中等专业学校</td>
    <td>宜宾职业技术学院</td>
  </tr>
  <tr>
    <td>广西桂东机电工程学校</td>
    <td>广西南宁市第一中等职业学校</td>
    <td>泸州职业技术学院</td>
  </tr>
  <tr>
    <td>钦州市机电工程学校</td>
    <td>博白县职业中等专业学校</td>
    <td>四川航天职业技术学院</td>
  </tr>
  <tr>
    <td>柳州铁路工业中等职业技术学校</td>
    <td>广西工学院</td>
    <td>成都农业科技职业学院</td>
  </tr>
  <tr>
    <td>桂林林业学校</td>
    <td>玉林市技工学校</td>
    <td>成都铁路运输学校</td>
  </tr>
  <tr>
    <td>柳州工程学校</td>
    <td>柳州第一职业技术学校</td>
    <td>四川省商贸学校</td>
  </tr>
  <tr>
    <td>梧州市机电技工学校</td>
    <td>广西城市职业学院</td>
    <td>四川省机电技术学校</td>
  </tr>
  <tr>
    <td>广西机械高级技工学校</td>
    <td>广西容县九0九电子科技学校</td>
    <td>内江铁路机械学校</td>
  </tr>
  <tr>
    <td>广西百色农业学校</td>
    <td>广西城市建设学校</td>
    <td>四川省宜宾市商业职业中等专业学校</td>
  </tr>
  <tr>
    <td>玉林市第一职业中等专业学校</td>
    <td>广西梧州商贸学校</td>
    <td>成都市礼仪职业中学</td>
  </tr>
  <tr>
    <td>广西生态工程职业技术学院</td>
    <td>广西经济管理干部学院</td>
    <td>成都市青苏职业中学</td>
  </tr>
  <tr>
    <td>桂林东方中等技术学校</td>
    <td>广西民族中等专业学校</td>
    <td>仁寿新科中等职业技术学校</td>
  </tr>
  <tr>
    <td>桂林市机电工程学校</td>
    <td>钟山县职业技术学校</td>
    <td>成都市规划设计研究院信息中心</td>
  </tr>
  <tr>
    <td>广西石化高级技工学校</td>
    <td>广西物资学校</td>
    <td>川大大地计算机学校</td>
  </tr>
  <tr>
    <td>北海市中等职业技术学校</td>
    <td>广西玉林华港中等职业技术学校</td>
    <td>华夏电脑信息技术培训学校</td>
  </tr>
  <tr>
    <td>广西水产畜牧学校</td>
    <td>桂林高级技工学校</td>
    <td align="center"><strong>重庆</strong></td>
  </tr>
  <tr>
    <td>百色职业学院</td>
    <td>桂林市重工威达技工学校</td>
    <td>重庆渝北职业教育中心</td>
  </tr>
  <tr>
    <td>横县职教中心</td>
    <td>武鸣县中等职业学校</td>
    <td>西南大学</td>
  </tr>
  <tr>
    <td> 柳州地区经济管理干部学校</td>
    <td>河池职业学院</td>
    <td>重庆职业技术学院</td>
  </tr>
  <tr>
    <td>浦北县第一职业技术学校</td>
    <td>桂林电子科技大学信息科技学院</td>
    <td>重庆工学院汽车学院</td>
  </tr>
  <tr>
    <td>柳州地区技工学校</td>
    <td>武宣县职业技术学校</td>
    <td>重庆工商职业学院</td>
  </tr>
  <tr>
    <td>钟山县职业技术学校</td>
    <td>南宁市中兴机电工业学校</td>
    <td>重庆电子工程职业学院</td>
  </tr>
  <tr>
    <td>柳州市第二技工学校</td>
    <td>柳州市汽车运输技工学校</td>
    <td>重庆巴渝职业技术学院</td>
  </tr>
  <tr>
    <td>广西商业学校</td>
    <td>钦州学院</td>
    <td>重庆科创职业学院</td>
  </tr>
  <tr>
    <td>广西广播电视学校</td>
    <td>柳州市工业贸易职业技术学校</td>
    <td>重庆市龙门浩职业中学</td>
  </tr>
  <tr>
    <td>桂林工业职业技术学校</td>
    <td>巴马县职业教育中心</td>
    <td>重庆市轻工业学校</td>
  </tr>
  <tr>
    <td>广西华侨学校</td>
    <td>桂林市职业教育中心学校</td>
    <td>重庆市彭水职教中心</td>
  </tr>
  <tr>
    <td>广西理工职业技术学校</td>
    <td>平南县科技中等专业学校</td>
    <td>重庆金龙计算机学校</td>
  </tr>
  <tr>
    <td>广西建设职业技术学院</td>
    <td>广西电子技工学校</td>
    <td>重庆东方电脑艺术学校</td>
  </tr>
  <tr>
    <td>容县职业中等专业学校</td>
    <td>容县职业中等专业学校</td>
    <td>重庆市渝北区远大计算机职业培训学校</td>
  </tr>
  <tr>
    <td>南宁市理工学校</td>
    <td>大化县职业技术学校</td>
    <td>重庆电子工程职业学院培训与继续教育学院</td>
  </tr>
  <tr>
    <td>贵港市职教中心</td>
    <td>崇左市职业技术学校</td>
    <td align="center"><strong>贵州</strong></td>
  </tr>
  <tr>
    <td>广西工商职业技术学院</td>
    <td>广西柳州钢铁（集团）公司高级技工学校</td>
    <td>贵州省遵义市职业技术学校</td>
  </tr>
  <tr>
    <td>融安县中等职业技术学校</td>
    <td>玉林市岭南工业学校</td>
    <td>遵义航天工业学校</td>
  </tr>
  <tr>
    <td>宜州市民族职业中专学校</td>
    <td>柳州运输职业技术学院</td>
    <td>贵州省电子工业学校</td>
  </tr>
  <tr>
    <td>梧州市新时代服装设计学校</td>
    <td>广西演艺职业学院</td>
    <td>贵州省水利电力学校</td>
  </tr>
  <tr>
    <td>广西电力职业技术学院</td>
    <td>田林县中等职业技术学校</td>
    <td>贵州大学立人教育中心</td>
  </tr>
  <tr>
    <td>广西钦州农业学校</td>
    <td>广西梧州农业学校</td>
    <td>贵州清江外国语学校电脑教育中心</td>
  </tr>
  <tr>
    <td>广西南宁机电技工学校</td>
    <td>广西人才市场培训中心</td>
    <td align="center"><strong>云南</strong></td>
  </tr>
  <tr>
    <td>柳州第三职业技术学校</td>
    <td>玉林市机电工程学校</td>
    <td>云南曲靖应用技术学校</td>
  </tr>
  <tr>
    <td>玉林电子工业学校</td>
    <td>桂林理工大学</td>
    <td>云南省旅游学校</td>
  </tr>
  <tr>
    <td>广西金秀县职业技术学校</td>
    <td>宾阳县职业技术学院</td>
    <td>昆明市第二职业中等专业学校</td>
  </tr>
  <tr>
    <td>广西工商学校</td>
    <td>广西工商学校</td>
    <td>红河州蒙自县职业高级中学</td>
  </tr>
  <tr>
    <td>桂林电子科技大学北海校区</td>
    <td>广西玉林农业学校</td>
    <td>文山州文山县职业高级中学</td>
  </tr>
  <tr>
    <td>柳州机电工程学校</td>
    <td>桂林市职教中心学校</td>
    <td>楚雄州禄丰县职业高级中学</td>
  </tr>
  <tr>
    <td>广西玉林精英电脑学校</td>
    <td>天等县中等职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>扶绥县中等职业技术学校</td>
    <td>合浦县中等职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>北海市电子职业技术学校</td>
    <td>桂林民族职业技术学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>梧州学院</td>
    <td>广西英华国际职业学院</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>广西银行学校</td>
    <td>南宁机电工程学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>南宁市第六职业技术学校</td>
    <td>桂林市财贸管理干部中等专业学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>柳州机电工程学校</td>
    <td>南宁商贸学校</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>玉林敬民科技学校</td>
    <td>&nbsp;</td>
  </tr>
             </table>

           </div>
           <!--西北地区-->
           <div id="con_two_7">
             <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><strong>陕西</strong></td>
    <td align="center"><strong>甘肃</strong></td>
    <td align="center"><strong>宁夏</strong></td>
    <td align="center"><strong>新疆</strong></td>
    <td align="center"><strong>青海</strong></td>
  </tr>
  <tr>
    <td>西安理工大学高等技术学院</td>
    <td>甘肃煤炭工业学校</td>
    <td>宁夏机电工程学校</td>
    <td>新疆机电职业技术学院</td>
    <td>青海省工业职业技术学校</td>
  </tr>
  <tr>
    <td>陕西师范大学职院</td>
    <td>甘肃建筑职业技术学院</td>
    <td>宁夏交通学校</td>
    <td>新疆钢铁学校</td>
    <td>青海省重工业职业技术学校</td>
  </tr>
  <tr>
    <td>陕西铁路工程职业技术学院</td>
    <td>甘肃因特计算机学校</td>
    <td>宁夏三佳计算机职业技能培训学校</td>
    <td>乌鲁木齐铁路运输学校</td>
    <td>青海省水电职业技术学校</td>
  </tr>
  <tr>
    <td>南郑县职业教育中心</td>
    <td>兰州城市建设学校</td>
    <td>&nbsp;</td>
    <td>新疆化学工业学校</td>
    <td>青海省西宁市第一职业技术学校</td>
  </tr>
  <tr>
    <td>陕西省理工学校</td>
    <td>甘肃省水利水电学校</td>
    <td>&nbsp;</td>
    <td>新疆科信学院</td>
    <td>青海省西钢职业技术学校</td>
  </tr>
  <tr>
    <td>陕西银行学校</td>
    <td>甘肃省财贸学校</td>
    <td>&nbsp;</td>
    <td>新疆优仕教育培训中心</td>
    <td>西宁市世纪职业技术学校</td>
  </tr>
  <tr>
    <td>陕西省宝鸡文理学院计算机专修学校</td>
    <td>张掖市科普职业培训学校</td>
    <td>&nbsp;</td>
    <td>新疆大学现代教育技术中心</td>
    <td>西宁大通县职业技术学校</td>
  </tr>
  <tr>
    <td>西安雁塔朝阳计算机学校</td>
    <td>兰州摩尔计算机职业培训学校</td>
    <td>&nbsp;</td>
    <td>新疆友志教育培训中心</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>西安建大图形图像教育基地</td>
    <td>兰州兰翔教育中心</td>
    <td>&nbsp;</td>
    <td>乌鲁木齐市嘉年华电脑培训中心</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>宝鸡文理学院计算机专修学校</td>
    <td>甘肃支点计算机专修学校</td>
    <td>&nbsp;</td>
    <td>乌鲁木齐市博荟科译教育咨询有限公司</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>陕西省西安市阎良区卓高职业学校</td>
    <td>兰州连邦电脑培训学校</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>延安星联电脑网络有限公司</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>

           </div>
         </div>
            </div>
          </div>
        </div>
<!-- 右边 -->
</div>
</div>

